export const MainContentActions = {
  LOAD_USER_ALL_TWEETS: "LOAD_USER_ALL_TWEETS",
};

export const RightContentActions = {
  LOAD_USER_TRENDS: "LOAD_USER_TRENDS",
  LOAD_USER_FOLLOW_SUGGESTIONS: "LOAD_USER_FOLLOW_SUGGESTIONS",
};
